version: '2'
services:
    backend:
        build:
            context: ./Backend
        ports:
            - "5000:80"
        depends_on:
            - redis
    frontend:
        build:
            context: ./Client
        ports:
            - "80:80"
        depends_on:
            - backend
    redis:
        image: redis
        ports:
            - "6380:6379"